/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class BaoKeoBua extends javax.swing.JFrame {
    int diemMay = 0;
    int diemNguoi = 0;
    int nguoiChon, mayChon;
    String ketQua = "";
    public void khoiDong(){
        lblHoa.setVisible(false); // Làm ẩn đi hình 
        lblMayWin.setVisible(false);
        lblNguoiWin.setVisible(false);
        menuChaoBan.setText("Chào bạn "+ Connect.name);
    }
    /**
     * Creates new form BaoKeoBua
     */
    public BaoKeoBua() {
        initComponents();
        this.setLocationRelativeTo(null);
        khoiDong();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblDiemCuaMay = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDiemCuaNguoi = new javax.swing.JLabel();
        btnBao = new javax.swing.JButton();
        btnKeo = new javax.swing.JButton();
        btnBua = new javax.swing.JButton();
        lblNguoiWin = new javax.swing.JLabel();
        lblMayWin = new javax.swing.JLabel();
        lblHoa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuHuongDan = new javax.swing.JMenu();
        menuLichSu = new javax.swing.JMenu();
        menuTaoMoi = new javax.swing.JMenu();
        menuChaoBan = new javax.swing.JMenu();
        menuDangXuat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game kéo búa bao");
        setBackground(new java.awt.Color(51, 255, 51));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("ONE TWO THREE GAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(197, 35, 283, 32);

        lblDiemCuaMay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDiemCuaMay.setForeground(new java.awt.Color(255, 51, 51));
        lblDiemCuaMay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiemCuaMay.setText("0");
        getContentPane().add(lblDiemCuaMay);
        lblDiemCuaMay.setBounds(130, 100, 60, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Score: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 100, 57, 24);

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblHinh);
        lblHinh.setBounds(130, 200, 60, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/may_tinh.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 140, 200, 210);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/you.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 150, 200, 190);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setText("Score: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 100, 57, 24);

        lblDiemCuaNguoi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDiemCuaNguoi.setForeground(new java.awt.Color(255, 51, 51));
        lblDiemCuaNguoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiemCuaNguoi.setText("0");
        getContentPane().add(lblDiemCuaNguoi);
        lblDiemCuaNguoi.setBounds(480, 100, 60, 30);

        btnBao.setForeground(new java.awt.Color(255, 255, 255));
        btnBao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao1.png"))); // NOI18N
        btnBao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnBao);
        btnBao.setBounds(320, 280, 80, 70);

        btnKeo.setForeground(new java.awt.Color(255, 255, 255));
        btnKeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo1.png"))); // NOI18N
        btnKeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeoActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeo);
        btnKeo.setBounds(320, 130, 80, 70);

        btnBua.setForeground(new java.awt.Color(255, 255, 255));
        btnBua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua1.png"))); // NOI18N
        btnBua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnBua);
        btnBua.setBounds(320, 210, 80, 60);

        lblNguoiWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/you_win.png"))); // NOI18N
        getContentPane().add(lblNguoiWin);
        lblNguoiWin.setBounds(500, 400, 114, 120);

        lblMayWin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/may_win.png"))); // NOI18N
        getContentPane().add(lblMayWin);
        lblMayWin.setBounds(60, 400, 114, 120);

        lblHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoa.png"))); // NOI18N
        getContentPane().add(lblHoa);
        lblHoa.setBounds(270, 370, 151, 156);

        jMenu1.setText("Thông tin ");
        jMenuBar1.add(jMenu1);

        menuHuongDan.setText("Hướng dẫn");
        menuHuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuHuongDanMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuHuongDan);

        menuLichSu.setText("Lịch sử");
        menuLichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLichSuMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLichSu);

        menuTaoMoi.setText("Tạo mới");
        menuTaoMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTaoMoiMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuTaoMoi);
        jMenuBar1.add(menuChaoBan);

        menuDangXuat.setText("Đăng xuất");
        menuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDangXuatMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuDangXuat);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Kiểm tra người thắng
    public void kiemTra(){
        if(diemMay == 15 || diemNguoi == 15){
            ghiFile();
            int chon = JOptionPane.YES_OPTION;
            if(diemMay == 15){
                chon = JOptionPane.showConfirmDialog(null, "MÁY THẮNG rồi!!!\nBạn chơi nữa không?", 
                        "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
            if(diemNguoi == 15){
                chon = JOptionPane.showConfirmDialog(null, "Bạn THẮNG rồi!!!\nBạn chơi nữa không?", 
                        "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
            if(chon == JOptionPane.NO_OPTION)
                this.dispose();
            else{
                diemMay = diemNguoi = 0;
                lblDiemCuaMay.setText("0");
                lblDiemCuaNguoi.setText("0");
                ketQua = "";
                khoiDong();
            }
            
        }
    }
    
    private void btnKeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeoActionPerformed
        Random rd = new Random();
        nguoiChon = 1;
        int random = rd.nextInt(3)+1;
        lblHoa.setVisible(false);
        lblMayWin.setVisible(false);
        lblNguoiWin.setVisible(false);
        if(random == 1){
            lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo.png")));
            lblHoa.setVisible(true);
        }else{
            if(random == 2){
                diemMay++;
                lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua.png")));
                lblMayWin.setVisible(true);
            }else{
                diemNguoi++;
                lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png")));
                lblNguoiWin.setVisible(true);
            }           
        }
        lblDiemCuaMay.setText(Integer.toString(diemMay));
        lblDiemCuaNguoi.setText(Integer.toString(diemNguoi));
        kiemTra();
    }//GEN-LAST:event_btnKeoActionPerformed

    private void btnBuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuaActionPerformed
        Random rd = new Random();
        nguoiChon = 2;
        int random = rd.nextInt(3)+1;
        lblHoa.setVisible(false);
        lblMayWin.setVisible(false);
        lblNguoiWin.setVisible(false);
        if(random == 1){
            diemNguoi++;
            lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo.png")));
            lblNguoiWin.setVisible(true);         
        }else{
            if(random == 2){
                lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua.png")));
                lblHoa.setVisible(true);
            }else{
                diemMay++;
                lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png")));
                lblMayWin.setVisible(true);
            }           
        }
        lblDiemCuaMay.setText(Integer.toString(diemMay));
        lblDiemCuaNguoi.setText(Integer.toString(diemNguoi));
        kiemTra();
    }//GEN-LAST:event_btnBuaActionPerformed

    private void btnBaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoActionPerformed
        Random rd = new Random();
        nguoiChon = 3;
        int random = rd.nextInt(3)+1;
        lblHoa.setVisible(false);
        lblMayWin.setVisible(false);
        lblNguoiWin.setVisible(false);
        if(random == 1){
            diemMay++;
            lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keo.png")));
            lblMayWin.setVisible(true);         
        }else{
            if(random == 2){
                diemNguoi++;
                lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bua.png")));
                lblNguoiWin.setVisible(true);
            }else{
                lblHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bao.png")));
                lblHoa.setVisible(true);
            }           
        }
        lblDiemCuaMay.setText(Integer.toString(diemMay));
        lblDiemCuaNguoi.setText(Integer.toString(diemNguoi));
        kiemTra();    
    }//GEN-LAST:event_btnBaoActionPerformed

    private void menuHuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuHuongDanMouseClicked
        HuongDan_KeoBuaBao a = new HuongDan_KeoBuaBao();
        a.setVisible(true);
    }//GEN-LAST:event_menuHuongDanMouseClicked

    private void menuTaoMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTaoMoiMouseClicked
        int kq = JOptionPane.showConfirmDialog(null, "Bạn muốn tạo mới game ?","Question",
                JOptionPane.YES_NO_OPTION);
        if(kq == 0)
        {
            lblDiemCuaMay.setText("0");
            lblDiemCuaNguoi.setText("0");
            diemMay = 0;
            diemNguoi = 0;
            lblHoa.setVisible(false);
            lblMayWin.setVisible(false);
            lblNguoiWin.setVisible(false);
        }
    }//GEN-LAST:event_menuTaoMoiMouseClicked

    private void menuDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDangXuatMouseClicked
        Connect.name = "";
        // in ra câu thông báo  coi có mún thoát trò chơi không
        int a = JOptionPane.showConfirmDialog(null, "Bạn muốn đăng xuất khỏi game oẳn tù tì?", 
                "Thông báo",JOptionPane.YES_NO_OPTION); 
        if( a == 0){
            DangNhap b = new DangNhap();
            b.setVisible(true);
            this.dispose();
        }
            
    }//GEN-LAST:event_menuDangXuatMouseClicked

    private void menuLichSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLichSuMouseClicked
        LichSuKeoBuaBao a = new LichSuKeoBuaBao();
        a.setVisible(true);
        a.setLocationRelativeTo(this);
    }//GEN-LAST:event_menuLichSuMouseClicked
    
    public void ghiFile(){
        ketQua = diemMay > diemNguoi ? "Machine Win" : Connect.name + " Win";
        String errConnect = Connect.getConnection();
        if(!errConnect.equals("")){
            JOptionPane.showMessageDialog(this, errConnect, "Lỗi kết nối", JOptionPane.ERROR_MESSAGE); 
            return;}
        String sql = "{call GhiLichsuOanTuTi(?,?,?,?,?,?)}";
        CallableStatement a;
        String kq;
        try {
            a = Connect.conn.prepareCall(sql);
            a.setString(1, "Game oẳn tù tì");
            a.setInt(2, diemMay);
            a.setInt(3, diemNguoi);
            a.setString(4, ketQua);
            a.setString(5, Connect.UserID);
            a.registerOutParameter(6, java.sql.Types.NVARCHAR);
            a.execute();
            kq = a.getString(6);
            JOptionPane.showMessageDialog(this, kq, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            a.close();
            Connect.conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }     
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoKeoBua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoKeoBua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoKeoBua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoKeoBua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoKeoBua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBao;
    private javax.swing.JButton btnBua;
    private javax.swing.JButton btnKeo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblDiemCuaMay;
    private javax.swing.JLabel lblDiemCuaNguoi;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblHoa;
    private javax.swing.JLabel lblMayWin;
    private javax.swing.JLabel lblNguoiWin;
    private javax.swing.JMenu menuChaoBan;
    private javax.swing.JMenu menuDangXuat;
    private javax.swing.JMenu menuHuongDan;
    private javax.swing.JMenu menuLichSu;
    private javax.swing.JMenu menuTaoMoi;
    // End of variables declaration//GEN-END:variables
}
