/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;


import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DoanSo extends javax.swing.JFrame {

    /**
     * Creates new form DoanSo
     */
    public DoanSo() {
        initComponents();
        this.setLocationRelativeTo(null);
        for(int i = 0; i <= 51; i++)
            cb1.addItem(Integer.toString(i));
        menuChaoBan.setText("Chào bạn "+ Connect.name);
    }
    int dem = 0, diem = 100;
    public void khoiDong(){
        dem = 0;
        diem = 100;
        lblKetQua.setText("");
        lblDoan.setText(Integer.toString(dem));
        lblDiem.setText(Integer.toString(diem));     
    }
    public void ghiFile(){
        String errConnect = Connect.getConnection();
        if(!errConnect.equals("")){
            JOptionPane.showMessageDialog(this, errConnect, "Lỗi kết nối", JOptionPane.ERROR_MESSAGE); 
            return;
        }
        String sql = "{call GhiLichsuDoanSo(?,?,?,?,?)}";
        CallableStatement a;
        String kq;
        try {
            a = Connect.conn.prepareCall(sql);
            a.setString(1, "Game đoán số");
            a.setInt(2, dem);
            a.setInt(3, diem);
            a.setString(4, Connect.UserID);
            a.registerOutParameter(5, java.sql.Types.NVARCHAR);
            a.execute();
            kq = a.getString(5);
            JOptionPane.showMessageDialog(this, kq, "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            a.close();
            Connect.conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox<>();
        lblKetQua = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRandom = new javax.swing.JLabel();
        btnBatDau = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtDoanSo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblDiem = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblDoan = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        menuChaoBan = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Game đoán số");
        setMinimumSize(new java.awt.Dimension(475, 570));
        setPreferredSize(new java.awt.Dimension(475, 570));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Máy phát sinh số từ ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 27, 129, 19);

        cb1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(175, 22, 79, 29);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("đến");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(286, 27, 24, 19);

        cb2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(cb2);
        cb2.setBounds(340, 22, 79, 29);

        lblKetQua.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblKetQua.setForeground(new java.awt.Color(51, 255, 51));
        lblKetQua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblKetQua);
        lblKetQua.setBounds(170, 160, 120, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/may_tinh.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 130, 200, 200);
        getContentPane().add(lblRandom);
        lblRandom.setBounds(171, 160, 120, 70);

        btnBatDau.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBatDau.setText("Bắt đầu");
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatDau);
        btnBatDau.setBounds(340, 69, 79, 35);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Bạn đoán số:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 350, 100, 19);

        txtDoanSo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtDoanSo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDoanSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoanSoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDoanSo);
        txtDoanSo.setBounds(120, 380, 210, 27);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kết quả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Số lần bạn đoán:");

        lblDiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDiem.setForeground(new java.awt.Color(255, 0, 204));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Tổng điểm:");

        lblDoan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblDoan.setForeground(new java.awt.Color(255, 51, 51));
        lblDoan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDoan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(lblDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 430, 420, 70);

        jMenu1.setText("Thông tin");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu1KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hướng dẫn");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Lịch sử");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Tạo mới");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);
        jMenuBar1.add(menuChaoBan);

        jMenu5.setText("Đăng xuất");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtDoanSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoanSoActionPerformed
        int soMay = Integer.parseInt(lblRandom.getText());int soNguoi = Integer.parseInt(txtDoanSo.getText());
        while(true){
            if(soNguoi == soMay){
                dem++;lblKetQua.setText("Correct!!!");lblDoan.setText(Integer.toString(dem));lblDiem.setText(Integer.toString(diem));
                ghiFile();
                int chon = JOptionPane.YES_OPTION;
                if(diem != 0)
                    chon = JOptionPane.showConfirmDialog(null, "Bạn đoán đúng rồi!!!\nBạn chơi nữa không?", 
                        "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(diem == 0)
                    chon = JOptionPane.showConfirmDialog(null, "Bạn thua rồi!!!\nBạn chơi nữa không?", 
                        "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if(chon == JOptionPane.NO_OPTION)this.dispose();else khoiDong();break;
            }
            else if(soNguoi < soMay){
                dem++;lblKetQua.setText("<html><b>Lớn hơn nha</b>");txtDoanSo.setText("");txtDoanSo.requestFocus();
                if(diem == 0){
                    JOptionPane.showMessageDialog(null, "Bạn đã thua", 
                            "Thông báo", JOptionPane.YES_OPTION);
                    ghiFile();
                    int chon = JOptionPane.YES_OPTION;
                    chon = JOptionPane.showConfirmDialog(null, "Bạn thua rồi!!!\nBạn chơi nữa không?", 
                            "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if(chon == JOptionPane.NO_OPTION) System.exit(0);else khoiDong();break;
                }
                else{lblDoan.setText(Integer.toString(dem));diem = diem - 10;lblDiem.setText(Integer.toString(diem));}break;
            }else{
                dem++;lblKetQua.setText("<html><b>Nhỏ hơn nha</b>");txtDoanSo.setText("");txtDoanSo.requestFocus();
                if(diem == 0){
                    JOptionPane.showMessageDialog(null, "Bạn đã thua", "Thông báo", JOptionPane.YES_OPTION);
                    ghiFile(); int chon = JOptionPane.YES_OPTION;
                    chon = JOptionPane.showConfirmDialog(null, "Bạn thua rồi!!!\nBạn chơi nữa không?", 
                            "Thông báo", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if(chon == JOptionPane.NO_OPTION)System.exit(0);else khoiDong();break;
                }
                else{lblDoan.setText(Integer.toString(dem));diem = diem - 10;lblDiem.setText(Integer.toString(diem));} break;}}     
    }//GEN-LAST:event_txtDoanSoActionPerformed
    
    
    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        int a = Integer.parseInt(cb1.getSelectedItem().toString());
        int b = Integer.parseInt(cb2.getSelectedItem().toString()); 
        if(a == b){
            JOptionPane.showMessageDialog(null, "Không được chọn 2 số giống nhau");
        }else{
            Random rd = new Random();
            int random = (rd.nextInt(b-a)) + a;
            lblRandom.setText(Integer.toString(random));       
            lblDoan.setText("0");
            lblDiem.setText("100");
        }        
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        cb2.removeAllItems();
        for(int i = Integer.parseInt(cb1.getSelectedItem().toString()); i < 50; i++){
            cb2.addItem(Integer.toString(i));
        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
            
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu1KeyPressed

    }//GEN-LAST:event_jMenu1KeyPressed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        HuongDanGameDoanSo a = new HuongDanGameDoanSo();
        a.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        int kq = JOptionPane.showConfirmDialog(null, "Bạn muốn tạo mới game ?","Question",JOptionPane.YES_NO_OPTION);
        if(kq == 0)
        {
            cb1.setSelectedIndex(0);
            cb2.setSelectedIndex(0);
            diem = 100;
            dem = 0;
            lblKetQua.setText("");
            txtDoanSo.setText("");
            lblDiem.setText("100");
            lblDoan.setText("0");
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        Connect.name = "";
        // in ra câu thông báo  coi có mún thoát trò chơi không
        int a = JOptionPane.showConfirmDialog(null, "Bạn muốn đăng xuất khỏi game đoán số?", "Thong báo",JOptionPane.YES_NO_OPTION); 
        if( a == 0){
            DangNhap b = new DangNhap();
            b.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        LichSuDoanSo a = new LichSuDoanSo();
        a.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoanSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoanSo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblDoan;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JLabel lblRandom;
    private javax.swing.JMenu menuChaoBan;
    private javax.swing.JTextField txtDoanSo;
    // End of variables declaration//GEN-END:variables
}
